return {
    the_woods_are_alive   ={front="dryads_.jpg",     back="back_f_2.jpg"},
    ancestors_legacy      ={front="dryads_2.jpg",    back="back_f_2.jpg"},
    forest                ={front="dryads_3.jpg",    back="back_f.jpg"},
    overtaking_overgrowth ={front="dryads_4.jpg",    back="back_f_1.jpg"},
    the_flowering         ={front="dryads_5.jpg",    back="back_f_f_4.jpg"},
    flytrap               ={front="dryads_6.jpg",    back="back_f_2.jpg"},
    primordial_tree       ={front="dryads_7.jpg",    back="back_f_f_3.jpg"},
    gliderkin             ={front="dryads_8.jpg",    back="back_f.jpg"},
    lithekin              ={front="dryads_9.jpg",    back="back_f_1.jpg"},
    vine_master           ={front="dryads_10.jpg",   back="back_f_2.jpg"},
    atashi_one_with_all   ={front="dryads_11.jpg",   back="back_f_2.jpg"},
    blight_thrower        ={front="dryads_12.jpg",   back="back_f_2.jpg"},
    hardwood_bludgeon     ={front="dryads_13.jpg",   back="back_f_3.jpg"},
    garnak                ={front="dryads_14.jpg",   back="back_f_f_3.jpg"},
    
	mine                  ={front="gearpunk_.jpg",   back="back_o.jpg"},
	uranium_purifier      ={front="gearpunk_2.jpg",  back="back_o_2.jpg"},
	gearpunk_factory      ={front="gearpunk_3.jpg",  back="back_o_1.jpg"},
    bomb_engine           ={front="gearpunk_4.jpg",  back="back_u_u_4.jpg"},
	city_module           ={front="gearpunk_5.jpg",  back="back_u_u_4.jpg"},
    command_pod           ={front="gearpunk_6.jpg",  back="back_u_u_4.jpg"},
	arachnohulk           ={front="gearpunk_7.jpg",  back="back_o_u_1.jpg"},
    axe_suit              ={front="gearpunk_8.jpg",  back="back_o_1.jpg"},
	gyropike              ={front="gearpunk_9.jpg",  back="back_o_u_1.jpg"},
    igor_mechanic_elect   ={front="gearpunk_10.jpg", back="back_o_o_2.jpg"},
	pistoleer             ={front="gearpunk_11.jpg", back="back_o_u_1.jpg"},
	shield_suit           ={front="gearpunk_13.jpg", back="back_o_2.jpg"},
    visionary_engineer    ={front="gearpunk_12.jpg", back="back_o_1.jpg"},
    
	kidnap                ={front="ice_dragons_.jpg",   back="back_e_2.jpg"},
	treasure_hoard        ={front="ice_dragons_2.jpg",  back="back_e_2.jpg"},
	unnatural_hail        ={front="ice_dragons_3.jpg",  back="back_e_2.jpg"},
    roost                 ={front="ice_dragons_4.jpg",  back="back_e.jpg"},
	dead_of_winter        ={front="ice_dragons_5.jpg",  back="back_e_2.jpg"},
    hatching_season       ={front="ice_dragons_6.jpg",  back="back_e_2.jpg"},
	ice_storm             ={front="ice_dragons_7.jpg",  back="back_e_2.jpg"},
    blade_statue          ={front="ice_dragons_8.jpg",  back="back_e_2.jpg"},
	blue_drake            ={front="ice_dragons_9.jpg",  back="back_e_2.jpg"},
    fjolnir               ={front="ice_dragons_10.jpg", back="back_e_e_4.jpg"},
	frost_elder           ={front="ice_dragons_11.jpg", back="back_e_e_2.jpg"},
	ice_ancient           ={front="ice_dragons_12.jpg", back="back_e_e_3.jpg"},
    ice_hulk              ={front="ice_dragons_13.jpg", back="back_e_2.jpg"},
    icemage               ={front="ice_dragons_14.jpg", back="back_e.jpg"},
    unwinged              ={front="ice_dragons_15.jpg", back="back_e_2.jpg"},
    
    -- mine                  ={front="minotaurs_.jpg",   back="back_o.jpg"},
	-- uranium_purifier      ={front="minotaurs_2.jpg",  back="back_o_2.jpg"},
	-- gearpunk_factory      ={front="minotaurs_3.jpg",  back="back_o_1.jpg"},
    -- bomb_engine           ={front="minotaurs_4.jpg",  back="back_u_u_4.jpg"},
	-- city_module           ={front="minotaurs_5.jpg",  back="back_u_u_4.jpg"},
    -- command_pod           ={front="minotaurs_6.jpg",  back="back_u_u_4.jpg"},
	-- arachnohulk           ={front="minotaurs_7.jpg",  back="back_o_u_1.jpg"},
    -- axe_suit              ={front="minotaurs_8.jpg",  back="back_o_1.jpg"},
	-- gyropike              ={front="minotaurs_9.jpg",  back="back_o_u_1.jpg"},
    -- igor_mechanic_elect   ={front="minotaurs_10.jpg", back="back_o_o_2.jpg"},
	-- pistoleer             ={front="minotaurs_11.jpg", back="back_o_u_1.jpg"},
	-- shield_suit           ={front="minotaurs_13.jpg", back="back_o_2.jpg"},
    -- visionary_engineer    ={front="minotaurs_14.jpg", back="back_o_1.jpg"},
    -- visionary_engineer    ={front="minotaurs_15.jpg", back="back_o_1.jpg"},
}                      